USE [ECOMMERCE]
GO

/****** Object:  Table [ECOOMEERCE].[Address]    Script Date: 6/25/2025 10:11:12 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [ECOOMEERCE].[Address](
	[AddressID] [int] IDENTITY(1,1) NOT NULL,
	[HouseNo] [varchar](255) NOT NULL,
	[Street] [int] NOT NULL,
	[CustomerID] [int] NOT NULL,
	[ZipCodeID] [int] NOT NULL,
	[Area] [varchar](255) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[AddressID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

/****** Object:  Table [ECOOMEERCE].[City]    Script Date: 6/25/2025 10:11:12 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [ECOOMEERCE].[City](
	[CityID] [int] IDENTITY(1,1) NOT NULL,
	[CityName] [varchar](255) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[CityID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

/****** Object:  Table [ECOOMEERCE].[Country]    Script Date: 6/25/2025 10:11:12 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [ECOOMEERCE].[Country](
	[CountryID] [int] IDENTITY(1,1) NOT NULL,
	[CountryName] [varchar](255) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[CountryID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

/****** Object:  Table [ECOOMEERCE].[Customer]    Script Date: 6/25/2025 10:11:12 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [ECOOMEERCE].[Customer](
	[CustomerID] [int] IDENTITY(1,1) NOT NULL,
	[FirstName] [varchar](255) NOT NULL,
	[LastName] [varchar](255) NOT NULL,
	[DOB] [date] NOT NULL,
	[Email] [varchar](255) NOT NULL,
	[Password] [varchar](255) NOT NULL,
	[Contact] [varchar](255) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[CustomerID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

/****** Object:  Table [ECOOMEERCE].[Province]    Script Date: 6/25/2025 10:11:12 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [ECOOMEERCE].[Province](
	[ProvinceID] [int] IDENTITY(1,1) NOT NULL,
	[ProvinceName] [varchar](255) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ProvinceID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

/****** Object:  Table [ECOOMEERCE].[ZipCode]    Script Date: 6/25/2025 10:11:12 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [ECOOMEERCE].[ZipCode](
	[ZipCodeID] [int] IDENTITY(1,1) NOT NULL,
	[CityID] [int] NOT NULL,
	[ProvinceID] [int] NOT NULL,
	[CountryID] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ZipCodeID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [ECOOMEERCE].[Address]  WITH CHECK ADD FOREIGN KEY([CustomerID])
REFERENCES [ECOOMEERCE].[Customer] ([CustomerID])
GO

ALTER TABLE [ECOOMEERCE].[Address]  WITH CHECK ADD FOREIGN KEY([ZipCodeID])
REFERENCES [ECOOMEERCE].[ZipCode] ([ZipCodeID])
GO

ALTER TABLE [ECOOMEERCE].[ZipCode]  WITH CHECK ADD FOREIGN KEY([CityID])
REFERENCES [ECOOMEERCE].[City] ([CityID])
GO

ALTER TABLE [ECOOMEERCE].[ZipCode]  WITH CHECK ADD FOREIGN KEY([CountryID])
REFERENCES [ECOOMEERCE].[Country] ([CountryID])
GO

ALTER TABLE [ECOOMEERCE].[ZipCode]  WITH CHECK ADD FOREIGN KEY([ProvinceID])
REFERENCES [ECOOMEERCE].[Province] ([ProvinceID])
GO


